name: trab3
dependencies:
  - base
  - hspec
  
tests:
  q1:
    main: ./Root/Testes/TestesQ1.hs
    source-dirs: .
    ghc-options: "-threaded -main-is Root.Testes.TestesQ1"
  q2:
    main: ./Root/Testes/TestesQ2.hs
    source-dirs: .
    ghc-options: "-threaded -main-is Root.Testes.TestesQ2"
  q3:
    main: ./Root/Testes/TestesQ3.hs
    source-dirs: .
    ghc-options: "-threaded -main-is Root.Testes.TestesQ3"
  q4:
    main: ./Root/Testes/TestesQ4.hs
    source-dirs: .
    ghc-options: "-threaded -main-is Root.Testes.TestesQ4"
  q5:
    main: ./Root/Testes/TestesQ5.hs
    source-dirs: .
    ghc-options: "-threaded -main-is Root.Testes.TestesQ5"

